apiVersion: v1
kind: Pod
metadata:
  name: nginx-3gb-100mcpu
  labels:
    app: nginx-3gb-100mcpu
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      requests:
        memory: "3Gi"
        cpu: "100m"
      limits:
        memory: "3Gi"
        cpu: "100m"
    ports:
    - containerPort: 80