apiVersion: v1
kind: Pod
metadata:
  name: nginx-200mb-1cpu
  labels:
    app: nginx-200mb-1cpu
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      requests:
        memory: "200Mi"
        cpu: "1000m"
      limits:
        memory: "200Mi"
        cpu: "1000m"
    ports:
    - containerPort: 80